In [10]:

"""
Briar Doty
AMATH 584 - midterm
11/6/20
Full repository available at https://github.com/briardoty/amath584/midterm
"""

%matplotlib inline

import matplotlib.pyplot as plt
import numpy as np
import math
from functools import reduce

In [44]:
# V - LU decomposition with pivoting
def lu_decomp(A):
    
    # only works for square matrices
    m, n = A.shape
    if m != n:
        return -1
    
    # define result matrices
    L, U = np.zeros_like(A), np.copy(A)
    L_arr = []
    
    for k in range(m):
        
        # start with I for L_k
        L_k = np.identity(m)
        
        # update kth column below diagonals
        for j in range(k+1,m):
            L_k[j,k] = -U[j,k]/U[k,k]
            
        # store L_k
        L_arr.append(L_k)
        
        # update "A" using L_k, building U in the process
        U = L_k@U
         
    # update L
    L = np.copy(L_arr[0])
    L = np.linalg.inv(L)
    for Li in L_arr[1:]:
        Linv = np.linalg.inv(Li)
        L = L@Linv
        
    return L, U

In [45]:
# V - demonstrate functionality on pre-defined matrix
A = np.array([
    [1.,-2.,0],
    [-3.,-2.,1],
    [6.,0.,3.]
])

L, U = lu_decomp(A)
A_lu = L@U
print(f"L:\n {L}\n")
print(f"U:\n {U}\n")
print(f"A_lu:\n {A_lu}\n")


L:
 [[ 1.   0.   0. ]
 [-3.   1.   0. ]
 [ 6.  -1.5  1. ]]

U:
 [[ 1.  -2.   0. ]
 [ 0.  -8.   1. ]
 [ 0.   0.   4.5]]

A:
 [[ 1. -2.  0.]
 [-3. -2.  1.]
 [ 6.  0.  3.]]

A_lu:
 [[ 1. -2.  0.]
 [-3. -2.  1.]
 [ 6.  0.  3.]]



In [15]:
# V - demonstrate functionality on random matrix
m = 5
A = np.random.rand(m,m)

L, U = lu_decomp(A)
A_lu = L@U
print(L)
print(U)
print(A)
print(A_lu)

[[  1.           0.           0.        ]
 [ -0.42112604   1.           0.        ]
 [-12.38535966  10.64415258   1.        ]]
[[ 0.11539608  0.41102389  0.85714242]
 [ 0.          0.23203388  0.44478616]
 [ 0.          0.         -1.96863647]]
[[0.11539608 0.41102389 0.85714242]
 [0.0485963  0.40512674 0.80575115]
 [0.91195561 0.77844783 0.07084248]]
[[ 0.11539608  0.41102389  0.85714242]
 [-0.0485963   0.05894102  0.08382117]
 [-1.429222   -2.62087467 -7.85028188]]
